"""Replace AddNewPersonForm raw-fetch button with use:enhance form in +page.svelte."""

import sys

FILE = 'C:/workspace/scotuschat/project/app/src/routes/admin/pipeline/[job_id]/+page.svelte'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# Build old string using tab literals
T = '\t'

old_parts = [
    T*12 + '<!-- AddNewPersonForm: inline below dropdown when Add new person selected -->\n',
    T*12 + '{#if s.addingPerson}\n',
    T*13 + '<div style="margin-top: 12px; padding: 12px; background-color: #0f1117; border: 1px solid #334155; border-radius: 6px;">\n',
    T*14 + '<div style="margin-bottom: 8px;">\n',
    T*15 + '<label\n',
    T*16 + 'for="new-person-name-{rowKey}"\n',
    T*16 + 'style="display: block; font-size: 14px; font-weight: 400; color: #94a3b8; margin-bottom: 4px;"\n',
    T*15 + '>\n',
    T*16 + 'Full name\n',
    T*15 + '</label>\n',
    T*15 + '<input\n',
    T*16 + 'id="new-person-name-{rowKey}"\n',
    T*16 + 'type="text"\n',
    T*16 + 'bind:value={s.newPersonName}\n',
    T*16 + 'style="\n',
    T*17 + 'background-color: #0f1117;\n',
    T*17 + 'border: 1px solid #334155;\n',
    T*17 + 'border-radius: 6px;\n',
    T*17 + 'padding: 8px 12px;\n',
    T*17 + 'font-size: 16px;\n',
    T*17 + 'color: #e2e8f0;\n',
    T*17 + 'width: 100%;\n',
    T*17 + 'box-sizing: border-box;\n',
    T*16 + '"\n',
    T*15 + '/>\n',
    T*14 + '</div>\n',
    T*14 + '<div style="margin-bottom: 12px;">\n',
    T*15 + '<label\n',
    T*16 + 'for="new-person-role-{rowKey}"\n',
    T*16 + 'style="display: block; font-size: 14px; font-weight: 400; color: #94a3b8; margin-bottom: 4px;"\n',
    T*15 + '>\n',
    T*16 + 'Role\n',
    T*15 + '</label>\n',
    T*15 + '<input\n',
    T*16 + 'id="new-person-role-{rowKey}"\n',
    T*16 + 'type="text"\n',
    T*16 + 'bind:value={s.newPersonRole}\n',
    T*16 + 'style="\n',
    T*17 + 'background-color: #0f1117;\n',
    T*17 + 'border: 1px solid #334155;\n',
    T*17 + 'border-radius: 6px;\n',
    T*17 + 'padding: 8px 12px;\n',
    T*17 + 'font-size: 16px;\n',
    T*17 + 'color: #e2e8f0;\n',
    T*17 + 'width: 100%;\n',
    T*17 + 'box-sizing: border-box;\n',
    T*16 + '"\n',
    T*15 + '/>\n',
    T*14 + '</div>\n',
    T*14 + '{#if s.newPersonError}\n',
    T*15 + '<p role="alert" style="color: #ef4444; font-size: 14px; margin: 0 0 8px 0;">\n',
    T*16 + '{s.newPersonError}\n',
    T*15 + '</p>\n',
    T*14 + '{/if}\n',
    T*14 + '<button\n',
    T*15 + 'type="button"\n',
    T*15 + 'disabled={s.submittingNewPerson || !s.newPersonName.trim()}\n',
    T*15 + 'onclick={() => handleAddPerson(rowKey)}\n',
    T*15 + 'style="\n',
    T*16 + 'font-size: 14px;\n',
    T*16 + 'font-weight: 600;\n',
    T*16 + 'color: #e2e8f0;\n',
    T*16 + 'background: transparent;\n',
    T*16 + 'border: 1px solid #93c5fd;\n',
    T*16 + 'border-radius: 6px;\n',
    T*16 + 'padding: 8px 16px;\n',
    T*16 + 'min-height: 36px;\n',
    T*16 + 'cursor: pointer;\n',
    T*15 + '"\n',
    T*14 + '>\n',
    T*15 + "{s.submittingNewPerson ? 'Saving…' : 'Save person'}\n",
    T*14 + '</button>\n',
    T*13 + '</div>\n',
    T*12 + '{/if}',
]

old = ''.join(old_parts)

new_parts = [
    T*12 + '<!-- AddNewPersonForm: inline below dropdown when Add new person selected.\n',
    T*12 + '     Uses use:enhance so SvelteKit handles devalue deserialization\n',
    T*12 + '     automatically ([07-07] Gap 2 fix). -->\n',
    T*12 + '{#if s.addingPerson}\n',
    T*13 + '<div style="margin-top: 12px; padding: 12px; background-color: #0f1117; border: 1px solid #334155; border-radius: 6px;">\n',
    T*14 + '<form\n',
    T*15 + 'method="POST"\n',
    T*15 + 'action="?/addPerson"\n',
    T*15 + 'use:enhance={() => {\n',
    T*16 + 'const label = rowKey;\n',
    T*16 + 'const st = rowStates[label];\n',
    T*16 + 'if (st) {\n',
    T*17 + 'st.submittingNewPerson = true;\n',
    T*17 + 'st.newPersonError = null;\n',
    T*16 + '}\n',
    T*16 + 'return async ({ result }) => {\n',
    T*17 + 'const st2 = rowStates[label];\n',
    T*17 + 'if (!st2) return;\n',
    T*17 + "if (result.type === 'failure') {\n",
    T*18 + "st2.newPersonError = (result.data as { error?: string })?.error ?? 'Could not create person. Please try again.';\n",
    T*17 + "} else if (result.type === 'success') {\n",
    T*18 + '// use:enhance devalue-deserializes result.data automatically\n',
    T*18 + 'const person = (result.data as { person?: { id: number; full_name: string; role_name?: string | null } })?.person;\n',
    T*18 + 'if (person) {\n',
    T*19 + 'st2.extraCandidates = [...st2.extraCandidates, { id: person.id, full_name: person.full_name, role_name: person.role_name ?? null }];\n',
    T*19 + 'st2.person_id = person.id;\n',
    T*19 + "st2.disposition = 'corrected';\n",
    T*19 + 'st2.addingPerson = false;\n',
    T*19 + "st2.newPersonName = '';\n",
    T*19 + "st2.newPersonRole = '';\n",
    T*18 + '}\n',
    T*17 + '}\n',
    T*17 + 'st2.submittingNewPerson = false;\n',
    T*17 + '// Do NOT call update() with reset — that wipes rowStates\n',
    T*16 + '};\n',
    T*15 + '}}\n',
    T*14 + '>\n',
    T*15 + '<div style="margin-bottom: 8px;">\n',
    T*16 + '<label\n',
    T*17 + 'for="new-person-name-{rowKey}"\n',
    T*17 + 'style="display: block; font-size: 14px; font-weight: 400; color: #94a3b8; margin-bottom: 4px;"\n',
    T*16 + '>\n',
    T*17 + 'Full name\n',
    T*16 + '</label>\n',
    T*16 + '<input\n',
    T*17 + 'id="new-person-name-{rowKey}"\n',
    T*17 + 'name="full_name"\n',
    T*17 + 'type="text"\n',
    T*17 + 'bind:value={s.newPersonName}\n',
    T*17 + 'style="\n',
    T*18 + 'background-color: #0f1117;\n',
    T*18 + 'border: 1px solid #334155;\n',
    T*18 + 'border-radius: 6px;\n',
    T*18 + 'padding: 8px 12px;\n',
    T*18 + 'font-size: 16px;\n',
    T*18 + 'color: #e2e8f0;\n',
    T*18 + 'width: 100%;\n',
    T*18 + 'box-sizing: border-box;\n',
    T*17 + '"\n',
    T*16 + '/>\n',
    T*15 + '</div>\n',
    T*15 + '<div style="margin-bottom: 12px;">\n',
    T*16 + '<label\n',
    T*17 + 'for="new-person-role-{rowKey}"\n',
    T*17 + 'style="display: block; font-size: 14px; font-weight: 400; color: #94a3b8; margin-bottom: 4px;"\n',
    T*16 + '>\n',
    T*17 + 'Role\n',
    T*16 + '</label>\n',
    T*16 + '<input\n',
    T*17 + 'id="new-person-role-{rowKey}"\n',
    T*17 + 'name="role_name"\n',
    T*17 + 'type="text"\n',
    T*17 + 'bind:value={s.newPersonRole}\n',
    T*17 + 'style="\n',
    T*18 + 'background-color: #0f1117;\n',
    T*18 + 'border: 1px solid #334155;\n',
    T*18 + 'border-radius: 6px;\n',
    T*18 + 'padding: 8px 12px;\n',
    T*18 + 'font-size: 16px;\n',
    T*18 + 'color: #e2e8f0;\n',
    T*18 + 'width: 100%;\n',
    T*18 + 'box-sizing: border-box;\n',
    T*17 + '"\n',
    T*16 + '/>\n',
    T*15 + '</div>\n',
    T*15 + '{#if s.newPersonError}\n',
    T*16 + '<p role="alert" style="color: #ef4444; font-size: 14px; margin: 0 0 8px 0;">\n',
    T*17 + '{s.newPersonError}\n',
    T*16 + '</p>\n',
    T*15 + '{/if}\n',
    T*15 + '<button\n',
    T*16 + 'type="submit"\n',
    T*16 + 'disabled={s.submittingNewPerson || !s.newPersonName.trim()}\n',
    T*16 + 'style="\n',
    T*17 + 'font-size: 14px;\n',
    T*17 + 'font-weight: 600;\n',
    T*17 + 'color: #e2e8f0;\n',
    T*17 + 'background: transparent;\n',
    T*17 + 'border: 1px solid #93c5fd;\n',
    T*17 + 'border-radius: 6px;\n',
    T*17 + 'padding: 8px 16px;\n',
    T*17 + 'min-height: 36px;\n',
    T*17 + 'cursor: pointer;\n',
    T*16 + '"\n',
    T*15 + '>\n',
    T*16 + "{s.submittingNewPerson ? 'Saving…' : 'Save person'}\n",
    T*15 + '</button>\n',
    T*14 + '</form>\n',
    T*13 + '</div>\n',
    T*12 + '{/if}',
]

new = ''.join(new_parts)

if old not in content:
    # Diagnostic: find where the mismatch starts
    for i in range(0, min(len(old), len(content))):
        if content.find(old[:i+1]) == -1:
            print(f"Mismatch at position {i}: {repr(old[max(0,i-20):i+20])}")
            break
    sys.exit(1)

new_content = content.replace(old, new, 1)
assert new_content != content, "No replacement made"

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("SUCCESS: AddNewPersonForm replaced with use:enhance form")
